--CREATE TABLE music(ID INTEGER NOT NULL PRIMARY KEY, title TEXT NOT NULL, artist TEXT NOT NULL, album TEXT NOT NULL, image TEXT NOT NULL, genre TEXT NOT NULL, audio TEXT NOT NULL);
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (0,'Billie Jean', 'Michael Jackson', 'Thriller', '/images/thriller.png', 'Pop', '/audio/billie.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (1, 'Cant Stop ', 'Red Hot Chilli Peppers', 'By The Way', '/images/rhcp.jpg', 'Rock', '/audio/cantstop.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (2, 'Bohemian Rhapsody', 'Queen', 'A Night At The Opera', '/images/opera.jpg', 'Pop', '/audio/bohemian.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (3, 'Breathe', 'Pink Floyd', 'The Dark Side Of The Moon', '/images/moon.jpg', 'Rock', '/audio/breathe.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (4, 'Smells Like Teen Spirit', 'Nirvana', 'Nevermind', '/images/nevermind.jpg', 'Rock', '/audio/smells.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (5, 'Blinding Lights', 'The Weeknd', 'After Hours', '/images/weeknd.jpg', 'Pop', '/audio/blinding.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (6, 'Even Flow', 'Pearl Jam', 'Ten', '/images/ten.jpg', 'Rock', '/audio/evenflow.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (7, 'Bold As Love', 'Jimi Hendrix', 'Axis: Bold As Love', '/images/jimi.jpg', 'Rock', '/audio/bold.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (8, 'Watermelon Sugar', 'Harry Styles', 'Fine Line', '/images/harry.jpg', 'Pop', '/audio/watermelon.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (9, 'Shape of You', 'Ed Sheeran', 'Divide', '/images/divide.jpg', 'Pop', '/audio/shape.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (10, 'Highway To Hell', 'AC/DC', 'Highway To Hell', '/images/acdc.jpg', 'Rock', '/audio/highway.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (11, 'California Love', '2Pac', 'All Eyez on Me', '/images/pac.jpg', 'Hip Hop', '/audio/california.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (12, 'In Da Club', '50 Cent', 'Get Rich Or Die Tryin', '/images/cent.jpg', 'Hip Hop', '/audio/club.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (13, 'Alright', 'Kendrick Lamar', 'To Pimp A Butterfly', '/images/tpab.jpg', 'Hip Hop', '/audio/alright.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (14, 'Without Me', 'Eminem', 'The Eminem Show', '/images/mm.jpg', 'Hip Hop', '/audio/withoutme.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (15, 'SUGAR', 'BROCKHAMPTON', 'GINGER', '/images/GINGER.jpg', 'Hip Hop', '/audio/sugar.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (16, 'If I Aint Got You', 'Alicia Keys', 'The Diary Of Alicia Keys', '/images/keys.jpg', 'R&B', '/audio/ifiaintgotyou.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (17, 'Die With A Smile', 'Lady Gaga, Bruno Mars', 'Die With A Smile', '/images/die.jpg', 'Pop', '/audio/diewithasmile.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (18, 'Thats What I Like', 'Bruno Mars', '24K Magic', '/images/24.jpg', 'Pop', '/audio/thatswhatilike.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (19, 'Here Comes The Sun', 'The Beatles', 'Abbey Road', '/images/abbey.jpg', 'Pop', '/audio/herecomesthesun.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (20, 'BIRDS OF A FEATHER', 'Billie Eilish', ' HIT ME HARD AND SOFT', '/images/billie.jpg', 'Pop', '/audio/birdsoffeather.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (21, 'Gravity', 'John Mayer', 'Continuum', '/images/continuum.jpg', 'R&B', '/audio/gravity.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (22, 'Around The World', 'Red Hot Chilli Peppers', 'Californication', '/images/cali.jpg', 'Rock', '/audio/aroundtheworld.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (23, 'So Into You', 'Tamia', 'Tamia', '/images/tamia.jpg', 'R&B', '/audio/sointoyou.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (24, 'Youre the One', 'SWV', 'New Beginning', '/images/swv.jpg', 'R&B', '/audio/youretheone.mp3');
INSERT INTO music (ID, title, artist, album, image, genre, audio) VALUES (25, 'No Scrubs', 'TLC', 'Fanmail', '/images/tlc.jpg', 'R&B', '/audio/noscrubs.mp3');
--SELECT * FROM music;